### PR TITLE
v2.1 Bug Fixes

### LINKED ISSUE #205: Parser drops explicitly quoted empty-string arguments
## Summary
The shell parser appears to discard explicitly quoted empty arguments.

## Reported in
- `docs/test_reports/tablehao_TestReport.md`
- `docs/test_reports/Novgor0d_TestReport_EdgeCases.md`

## Observed behaviour
- `ls ""` behaves like plain `ls`.
- `cd ''` is silently ignored instead of being treated as an explicit empty argument.

## Why this is a bug
An explicitly quoted empty string is still a real argument. Dropping it changes command semantics and makes parsing inconsistent with standard shell behaviour.

## Suggested direction
Review tokenization / argument preservation so that quoted empty strings survive parsing and are passed through to commands as empty arguments.

### LINKED ISSUE #209: Parser accepts commandless input without raising a syntax error
## Summary
Some inputs with no actual command are accepted silently instead of producing a syntax error.

## Reported in
- `docs/test_reports/Novgor0d_TestReport_EdgeCases.md`

## Observed behaviour
- `< nonexistent.txt` produces no output and no error.
- `;;;` produces no output and no error.

## Why this is a bug
The shell already reports syntax errors for many malformed operator cases. Silently accepting an empty command plan is inconsistent with the existing error handling model.

## Suggested direction
Tighten parser / plan validation so inputs with operators or redirections but no executable segment are rejected with a syntax error.

### LINKED ISSUE #215: Inconsistent formatting of help command output between shell modes
The output format of the help command differs depending on how it is invoked, leading to inconsistent and less readable output.

**Steps to reproduce**:

1. Run `help` in the main environment.
2. Start a shell session using shell.
3. Run `help` again inside the shell.

**Expected behavior**:
The help command should produce consistently formatted output across all contexts, using a readable layout with proper whitespace and alignment between command names and descriptions.

**Actual behavior**:
The formatting inside the shell differs, producing a more compact and less readable layout (e.g., command-desc style with reduced spacing).

### PR DESCRIPTION
**Pull request by Novgor0d**
This PR adds improved input validation for `AliasCommand` and `HistoryCommand`

Fixes #209

Fixes #205

Fixes #215

### CODE REVIEW

File: src/main/java/linuxlingo/shell/command/AliasCommand.java
Comment (puma-31) [inline src/main/java/linuxlingo/shell/command/AliasCommand.java:1]: Changes suggest detailed testing and analysis of commands. Good work!

File: src/main/java/linuxlingo/shell/command/CdCommand.java [hunk 1]
```diff
@@ -21,6 +21,11 @@ public CommandResult execute(ShellSession session, String[] args, String stdin)
         String currentDir = session.getWorkingDir();
         String target = args.length == 0 ? "~" : args[0];
 
+        // Explicitly quoted empty string is not a valid path
```
Comment (puma-31) [inline src/main/java/linuxlingo/shell/command/CdCommand.java:24]: Should you also consider blank inputs like whitespaces?

**Review by puma-31 — COMMENTED** [review]
Bug fixes are comprehensive and clear
